// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxfdlucjgngfzudjjsjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZmRsdWNqZ25nZnp1ZGpqc2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTAyMjIsImV4cCI6MjA2ODY2NjIyMn0.uV0ncs7RNKK6Jy_3J9UNxGJ-WnLYVYVADdtleERk-CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});